python:
  - "2.7"

script:
  - mkdir BUILD
# Assert that the Doxygen build produced no warnings.
# The strange command below asserts that the Doxygen command had an
# output of zero length
  - |
    doxygen doxyfile_options 2>&1 | tee BUILD/doxygen.out && [ ! -s BUILD/doxygen.out ]
# Assert that all binary libraries are named correctly
# The strange command below asserts that there are exactly 0 libraries that do
# not start with lib
  - |
    find "(" -name "*.a" -or -name "*.ar" ")" -and -not -name "lib*" | tee BUILD/badlibs | sed -e "s/^/Bad library name found: /" && [ ! -s BUILD/badlibs ]
# Assert that all assebler files are named correctly
# The strange command below asserts that there are exactly 0 libraries that do
# end with .s
  - |
    find  -name "*.s" | tee BUILD/badasm | sed -e "s/^/Bad Assembler file name found: /" && [ ! -s BUILD/badasm ]
  - make -C events/equeue test clean
  - PYTHONPATH=. python tools/test/config_test/config_test.py
  - PYTHONPATH=. python tools/test/build_api/build_api_test.py
  - PYTHONPATH=. python tools/test/targets/target_test.py
  - python tools/test/pylint.py
  - py.test tools/test/toolchains/api.py
  - python tools/test/memap/memap_test.py
  - python tools/project.py -S
  - python tools/build_travis.py
before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo add-apt-repository -y ppa:libreoffice/libreoffice-4-2
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi doxygen --force-yes
  # Print versions we use
  - arm-none-eabi-gcc --version
  - python --version
  - doxygen --version
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pylint
  - pip install hypothesis
  - pip install mock
